from __future__ import annotations

"""
RAG Query Pipeline — Post-Processor Component

Validates LLM outputs:
  1. Enforces response length constraints (<= 3 sentences)
  2. Extracts and validates the citation URL against chunk metadata
  3. Appends the "Last updated from sources: YYYY-MM-DD" footer
  4. Returns a clean structured dict format
"""

import re


class PostProcessor:
    """Class to post-process raw LLM answers."""

    def __init__(self, max_sentences: int = 3) -> None:
        """Initialize PostProcessor."""
        self.max_sentences = max_sentences

    def postprocess(
        self,
        raw_answer: str,
        retrieved_chunks: list[dict],
        fallback_msg: str = "I don't have enough information to answer this from my sources.",
    ) -> dict:
        """Validate and format the LLM answer.

        Args:
            raw_answer: The raw response text generated by the LLM.
            retrieved_chunks: The list of candidate chunks retrieved for the query.
            fallback_msg: The standard fallback message for unknown answers.

        Returns:
            Dict containing:
              - 'status': 'success'
              - 'type': 'factual'
              - 'answer': formatted sentence-limited text
              - 'citation': citation URL string or None
              - 'footer': last-updated footer string or empty string
        """
        # If LLM indicates failure or fallback
        if (
            fallback_msg.lower() in raw_answer.lower()
            or "[error]" in raw_answer.lower()
            or not retrieved_chunks
        ):
            return {
                "status": "success",
                "type": "factual",
                "answer": fallback_msg,
                "citation": None,
                "footer": "",
            }

        # 1. Enforce sentence limit (MAX_RESPONSE_SENTENCES = 3)
        # Regex splits on periods/exclamations/questions followed by spaces and capitalized words
        sentences = re.split(r"(?<=[.!?])\s+(?=[A-Z0-9])|(?<=[.!?])\s*$", raw_answer.strip())
        sentences = [s.strip() for s in sentences if s.strip()]

        if len(sentences) > self.max_sentences:
            sentences = sentences[:self.max_sentences]
            
        clean_answer = " ".join(sentences)

        # 2. Extract and validate citation URL
        citation_url = None
        cited_chunk = None

        # Check if the LLM output explicitly cited one of the retrieved URLs
        for chunk in retrieved_chunks:
            url = chunk["metadata"].get("source_url")
            if url and url in clean_answer:
                citation_url = url
                cited_chunk = chunk
                break

        # Fallback check on raw_answer before sentence truncation
        if not citation_url:
            for chunk in retrieved_chunks:
                url = chunk["metadata"].get("source_url")
                if url and url in raw_answer:
                    citation_url = url
                    cited_chunk = chunk
                    break

        # If no explicit URL found in the text, default to the top-ranked chunk
        if not citation_url and retrieved_chunks:
            cited_chunk = retrieved_chunks[0]
            citation_url = cited_chunk["metadata"].get("source_url")

        # 3. Build the footer: Last updated from sources: <date>
        footer = ""
        if cited_chunk:
            meta = cited_chunk["metadata"]
            date_str = meta.get("downloaded_at") or meta.get("ingestion_date") or ""
            if date_str and len(date_str) >= 10:
                date_str = date_str[:10]  # format YYYY-MM-DD
            else:
                date_str = "N/A"
            footer = f"Last updated from sources: {date_str}"

        # Clean up any duplicated trailing URL citations in text for better UI presentation
        # but only if citation_url is returned separately in JSON
        if citation_url and citation_url in clean_answer:
            # Remove URL citation suffixes from the answer string to avoid double display in UI
            clean_answer = clean_answer.replace(citation_url, "").strip()
            
            # Clean up trailing words like Source, URL, Link, visit, or For more information
            clean_answer = re.sub(
                r"\s*(?:source|url|link|visit|for details|for more info|for more information)\s*[:\-\s]*\.?\s*$",
                "",
                clean_answer,
                flags=re.IGNORECASE,
            )
            # Clean up trailing brackets or parentheses that might have held the URL
            clean_answer = re.sub(r"\s*[(\[]\s*[)\]]\s*$", "", clean_answer)
            # Re-ensure ends with a period if it was stripped
            clean_answer = clean_answer.strip()
            if clean_answer and not clean_answer.endswith((".", "!", "?")):
                clean_answer += "."

        return {
            "status": "success",
            "type": "factual",
            "answer": clean_answer,
            "citation": citation_url,
            "footer": footer,
        }
