from __future__ import annotations

"""
Ingestion — Embedding + ChromaDB Indexer

Generates embeddings via ``sentence-transformers`` (BGE) and upserts
chunks into a persistent ChromaDB collection.

Key design decisions:
  • Embeddings are generated by ChromaDB's built-in ``SentenceTransformerEmbeddingFunction``
    so queries use the exact same model/tokenizer at retrieval time.
  • Upsert semantics — re-running ingestion safely replaces existing chunks
    with matching IDs instead of duplicating them.
  • Metadata is stored alongside embeddings for filtered retrieval.
"""

import chromadb
from chromadb.utils import embedding_functions

from src.config import (
    CHROMA_COLLECTION_NAME,
    CHROMA_PERSIST_DIR,
    EMBEDDING_MODEL_NAME,
)


# ───────────────────────────────────────────────────────────
# Embedding function (shared by indexer + retriever)
# ───────────────────────────────────────────────────────────

def get_embedding_function() -> embedding_functions.SentenceTransformerEmbeddingFunction:
    """Return a ChromaDB-compatible embedding function using the BGE model.

    The same function must be used at both index and query time so that
    vectors are comparable.
    """
    return embedding_functions.SentenceTransformerEmbeddingFunction(
        model_name=EMBEDDING_MODEL_NAME,
    )


# ───────────────────────────────────────────────────────────
# ChromaDB client + collection helpers
# ───────────────────────────────────────────────────────────

def get_chroma_client() -> chromadb.PersistentClient:
    """Return a ChromaDB persistent client."""
    return chromadb.PersistentClient(path=CHROMA_PERSIST_DIR)


def get_or_create_collection(
    client: chromadb.PersistentClient | None = None,
    collection_name: str | None = None,
) -> chromadb.Collection:
    """Get or create the ChromaDB collection with the BGE embedding function.

    Args:
        client:          Optional pre-existing client (creates one if *None*).
        collection_name: Override the default collection name.

    Returns:
        A ChromaDB ``Collection`` ready for upsert / query.
    """
    client = client or get_chroma_client()
    name = collection_name or CHROMA_COLLECTION_NAME
    ef = get_embedding_function()

    collection = client.get_or_create_collection(
        name=name,
        embedding_function=ef,
        metadata={"hnsw:space": "cosine"},  # cosine similarity
    )
    return collection


# ───────────────────────────────────────────────────────────
# Indexing
# ───────────────────────────────────────────────────────────

def _sanitize_metadata(meta: dict) -> dict:
    """Ensure all metadata values are ChromaDB-safe (str | int | float | bool).

    ChromaDB rejects ``None``, lists, and nested dicts.
    """
    clean: dict = {}
    for key, val in meta.items():
        if val is None:
            continue
        if isinstance(val, (str, int, float, bool)):
            clean[key] = val
        else:
            clean[key] = str(val)
    return clean


_BATCH_SIZE = 100  # ChromaDB performs better with batched upserts


def index_chunks(
    chunks: list[dict],
    collection: chromadb.Collection | None = None,
    batch_size: int = _BATCH_SIZE,
) -> int:
    """Upsert a list of chunk dicts into ChromaDB.

    Each chunk dict must have:
      - ``text``:     The chunk content (used as the ``document``).
      - ``chunk_id``: Unique ID (used as the ChromaDB ``id``).
      - Any other keys become metadata.

    Args:
        chunks:     List of chunk dicts from the chunker.
        collection: Optional pre-existing collection.
        batch_size: Number of chunks per upsert call.

    Returns:
        Total number of chunks upserted.
    """
    if not chunks:
        return 0

    coll = collection or get_or_create_collection()

    total = 0
    for i in range(0, len(chunks), batch_size):
        batch = chunks[i : i + batch_size]

        ids = []
        documents = []
        metadatas = []

        for chunk in batch:
            ids.append(chunk["chunk_id"])
            documents.append(chunk["text"])

            # Everything except text and chunk_id goes into metadata
            meta = {k: v for k, v in chunk.items() if k not in ("text", "chunk_id")}
            metadatas.append(_sanitize_metadata(meta))

        coll.upsert(
            ids=ids,
            documents=documents,
            metadatas=metadatas,
        )
        total += len(batch)

    return total


def clear_collection(collection_name: str | None = None) -> None:
    """Delete and recreate the collection (useful for clean re-ingestion).

    Args:
        collection_name: Override the default collection name.
    """
    client = get_chroma_client()
    name = collection_name or CHROMA_COLLECTION_NAME
    try:
        client.delete_collection(name)
    except Exception:
        pass  # collection doesn't exist yet — that's fine
    # recreate
    get_or_create_collection(client, name)


def get_collection_stats(collection_name: str | None = None) -> dict:
    """Return basic stats about the collection.

    Returns:
        Dict with ``count``, ``collection_name``, and ``persist_dir``.
    """
    coll = get_or_create_collection(collection_name=collection_name)
    return {
        "collection_name": coll.name,
        "count": coll.count(),
        "persist_dir": CHROMA_PERSIST_DIR,
    }
